// Generated by png2bitmap_rgb565_c_h_pragonce.py
#pragma once

#include <stdint.h>

typedef struct bitmap {
    uint16_t width;
    uint16_t height;
    uint16_t* bitmap;
} bitmap;

extern const bitmap emoji_bitmap;
